[package]
name = "webview_app"
version = "0.1.0"
description = "Simple integration of a web view in an application window like Electron"
authors = ["Uwe Riegel <uriegel@hotmail.de>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/uriegel/webview-app"
readme = "README.md"

[target.'cfg(target_os="linux")'.dependencies]
gtk = "0.9"
gio = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "3.0"

