[package]
name = "webview_app"
version = "1.2.1"
keywords = ["WebView", "webview2", "webkit", "Windows", "Linux"]
categories = ["gui"]
description = "Simple integration of a web view in an application window for windows and linux similar to Electron"
authors = ["Uwe Riegel <uriegel@hotmail.de>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/uriegel/webview-app"
documentation = "https://uriegel.github.io/webview-app"
readme = "README_CRATE.md"
include = [
    "src/**/*",
    "assets/**/*",
    "Cargo.toml"
]

[dependencies]
include_dir = "0.7.4"
serde = { version = "1.0.229", features = [ "derive" ] }
serde_json = "1.0.151"

[target.'cfg(target_os="linux")'.dependencies]
gtk = { version = "0.11.4", package = "gtk4", features = ["v4_14"]}
adw = { version = "0.9.2", package = "libadwaita", features = ["v1_5"] }
webkit6 = "0.6.1"
async-channel = "2.5.0"

[target.'cfg(target_os="windows")'.dependencies]
webview2-com = "0.39.1"
windows-implement = "0.60"
windows-interface = "0.59"
windows-core = "0.62.2"
windows = { version = "0.62", features = [
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
    "Win32_System_Threading",
    "Win32_UI_HiDpi",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
]}
windows-sys = {version = "0.61", features = [
    "Win32_UI_Shell",
]}
