[package]
name = "webview_app"
version = "0.3.2"
description = "Simple integration of a web view in an application window like Electron"
authors = ["Uwe Riegel <uriegel@hotmail.de>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/uriegel/webview-app"
readme = "README.md"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "3.0"
tokio = { version = "1.5", features = ["full"] }
warp = "0.3"
chrono = "0.4"

[target.'cfg(target_os="linux")'.dependencies]
gtk = "0.9"
gio = "0.9"
webkit2gtk = "0.11"
webkit2gtk-sys = "0.13"

[target.'cfg(target_os="windows")'.dependencies]
winapi = { version = "0.3.9", features = [
    "libloaderapi", "winuser", "wincodec"
]}
winit = "0.25"
webview2 = "0.1"
once_cell = "1.7"



