[package]
name = "windows_titlebar"
version = "0.1.0"
edition = "2021"

[dependencies]
webview_app = { path = "../../../webview-app" }
include_dir = "0.7.4"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
